#!/usr/bin/env python
import os
import sys
import argparse

def parse_arguments():
    parser = argparse.ArgumentParser(description='Process and merge classification files.')
    parser.add_argument('-i', '--input', required=True, nargs='+', dest='in_files',
                        help='Input files for this program (files generated by kreport2mpa.py)')
    parser.add_argument('-o', '--output', required=True, dest='o_file',
                        help='Single mpa-report file name')
    return parser.parse_args()

def extract_sample_name(file_name):
    parts = file_name.split('.')
    if len(parts) > 1:
        return parts[1]  # Extract the second part
    return file_name  # Fallback in case of an unexpected format

def process_file(in_file, sample_name, samples, values, parent2child, toparse):
    try:
        with open(in_file, 'r') as i_file:
            for line in i_file:
                if line.startswith("#"):
                    continue
                classification, val = line.strip().split('\t')
                split_vals = classification.split("|")
                curr_parent = ''
                for i in range(len(split_vals)):
                    test_val = "|".join(split_vals[:i])
                    if test_val in values:
                        curr_parent = test_val
                if curr_parent == '':
                    if classification not in values:
                        toparse.append(classification)
                else:
                    if curr_parent not in parent2child:
                        parent2child[curr_parent] = []
                    if classification not in parent2child[curr_parent]:
                        parent2child[curr_parent].append(classification)
                if classification not in values:
                    values[classification] = {}
                values[classification][sample_name] = val
            samples.add(sample_name)
    except FileNotFoundError:
        sys.stderr.write(f"Error: File {in_file} not found.\n")
    except Exception as e:
        sys.stderr.write(f"Error processing file {in_file}: {e}\n")

def write_output(o_file, samples, values, parent2child, toparse):
    try:
        with open(o_file, 'w') as out_file:
            out_file.write("#Classification")
            for sample in sorted(samples):
                out_file.write(f"\t{sample}")
            out_file.write("\n")
            count_c = 0
            while toparse:
                curr_c = toparse.pop(0)
                if curr_c in parent2child:
                    for child in parent2child[curr_c]:
                        toparse.insert(0, child)
                out_file.write(curr_c)
                for sample in sorted(samples):
                    out_file.write(f"\t{values[curr_c].get(sample, '0')}")
                out_file.write("\n")
                count_c += 1
                sys.stdout.write(f"\r\t{count_c} classifications printed")
                sys.stdout.flush()
    except Exception as e:
        sys.stderr.write(f"Error writing to file {o_file}: {e}\n")

def main():
    args = parse_arguments()
    samples = set()
    values = {}
    parent2child = {}
    toparse = []

    sys.stdout.write(f"Number of files to parse: {len(args.in_files)}\n")

    for in_file in args.in_files:
        sample_name = extract_sample_name(os.path.basename(in_file))
        process_file(in_file, sample_name, samples, values, parent2child, toparse)

    sys.stdout.write(f"Number of classifications to write: {len(values)}\n")
    sys.stdout.write("\t0 classifications printed")

    write_output(args.o_file, samples, values, parent2child, toparse)

    sys.stdout.write(f"\r\t{len(values)} classifications printed\n")
    sys.stdout.flush()

if __name__ == "__main__":
    main()
